var json_stationmetroRER_13 = {
"type": "FeatureCollection",
"name": "stationmetroRER_13",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "full_id": "n12388528", "osm_id": "12388528", "osm_type": "node", "railway": "station", "type_RATP": "metro", "STIF_zone": "1", "wikipedia": "fr:Châtillon - Montrouge (métro de Paris)", "name": "Châtillon-Montrouge", "station": "subway", "wikidata": "Q1090894", "ref_FR_RAT": "1968", "route_ref_": null, "uic_ref": null, "wheelchair": null, "official_n": null, "operator": null, "name_ru": null, "network": null, "highway": null, "ref_FR_STI": null, "alt_name": null, "public_tra": null, "ref_FR_FAN": null, "subway": null, "mhs_inscri": null, "ref_mhs": null, "heritage": null, "heritage_o": null, "source_her": null, "rail": null, "importance": null, "train": null, "highspeed": null, "electrifie": null, "ref": null, "old_name": null, "railway_sw": null, "crossing_l": null, "crossing_b": null, "crossing": null, "descriptio": null, "level": null, "ref_FR_uic": null, "tram": null, "barrier": null, "covered": null, "tactile_pa": null, "platforms": null, "start_date": null, "traffic_si": null, "traffic__1": null, "constructi": null, "supervised": null, "source_ref": null, "bicycle": null, "entrance": null }, "geometry": { "type": "Point", "coordinates": [ 2.3015874, 48.8108097 ] } },
{ "type": "Feature", "properties": { "full_id": "n100295884", "osm_id": "100295884", "osm_type": "node", "railway": "station", "type_RATP": "rer", "STIF_zone": "3", "wikipedia": "fr:Gare d'Arcueil - Cachan", "name": "Arcueil-Cachan", "station": null, "wikidata": "Q1892192", "ref_FR_RAT": "1985", "route_ref_": null, "uic_ref": "8775867", "wheelchair": "yes", "official_n": null, "operator": "SNCF", "name_ru": null, "network": null, "highway": null, "ref_FR_STI": "412836", "alt_name": null, "public_tra": null, "ref_FR_FAN": null, "subway": null, "mhs_inscri": null, "ref_mhs": null, "heritage": null, "heritage_o": null, "source_her": null, "rail": null, "importance": null, "train": null, "highspeed": null, "electrifie": null, "ref": null, "old_name": null, "railway_sw": null, "crossing_l": null, "crossing_b": null, "crossing": null, "descriptio": null, "level": null, "ref_FR_uic": null, "tram": null, "barrier": null, "covered": null, "tactile_pa": null, "platforms": null, "start_date": null, "traffic_si": null, "traffic__1": null, "constructi": null, "supervised": null, "source_ref": null, "bicycle": null, "entrance": null }, "geometry": { "type": "Point", "coordinates": [ 2.3281001, 48.7986051 ] } },
{ "type": "Feature", "properties": { "full_id": "n166004531", "osm_id": "166004531", "osm_type": "node", "railway": "station", "type_RATP": "rer", "STIF_zone": "3", "wikipedia": "fr:Gare de Fontenay-aux-Roses", "name": "Fontenay-aux-Roses", "station": null, "wikidata": "Q2443290", "ref_FR_RAT": "1921", "route_ref_": null, "uic_ref": "8775871", "wheelchair": "yes", "official_n": null, "operator": null, "name_ru": null, "network": null, "highway": null, "ref_FR_STI": null, "alt_name": null, "public_tra": null, "ref_FR_FAN": null, "subway": null, "mhs_inscri": null, "ref_mhs": null, "heritage": null, "heritage_o": null, "source_her": null, "rail": null, "importance": null, "train": null, "highspeed": null, "electrifie": null, "ref": null, "old_name": null, "railway_sw": null, "crossing_l": null, "crossing_b": null, "crossing": null, "descriptio": null, "level": null, "ref_FR_uic": null, "tram": null, "barrier": null, "covered": null, "tactile_pa": null, "platforms": null, "start_date": null, "traffic_si": null, "traffic__1": null, "constructi": null, "supervised": null, "source_ref": null, "bicycle": null, "entrance": null }, "geometry": { "type": "Point", "coordinates": [ 2.2922257, 48.7876401 ] } },
{ "type": "Feature", "properties": { "full_id": "n3328627275", "osm_id": "3328627275", "osm_type": "node", "railway": "station", "type_RATP": null, "STIF_zone": null, "wikipedia": "fr:Gare de Bagneux", "name": "Bagneux", "station": null, "wikidata": "Q1958487", "ref_FR_RAT": "1996", "route_ref_": null, "uic_ref": null, "wheelchair": null, "official_n": null, "operator": null, "name_ru": null, "network": null, "highway": null, "ref_FR_STI": "412843", "alt_name": null, "public_tra": null, "ref_FR_FAN": null, "subway": null, "mhs_inscri": null, "ref_mhs": null, "heritage": null, "heritage_o": null, "source_her": null, "rail": null, "importance": null, "train": null, "highspeed": null, "electrifie": null, "ref": null, "old_name": null, "railway_sw": null, "crossing_l": null, "crossing_b": null, "crossing": null, "descriptio": null, "level": null, "ref_FR_uic": null, "tram": null, "barrier": null, "covered": null, "tactile_pa": null, "platforms": null, "start_date": null, "traffic_si": null, "traffic__1": null, "constructi": null, "supervised": null, "source_ref": "RATP - 07\/2012", "bicycle": null, "entrance": null }, "geometry": { "type": "Point", "coordinates": [ 2.3210038, 48.7932411 ] } },
{ "type": "Feature", "properties": { "full_id": "n2156465759", "osm_id": "2156465759", "osm_type": "node", "railway": "station", "type_RATP": "rer", "STIF_zone": "2", "wikipedia": "fr:Gare de Laplace", "name": "Laplace", "station": null, "wikidata": "Q782121", "ref_FR_RAT": "1880", "route_ref_": null, "uic_ref": "8775866", "wheelchair": "yes", "official_n": null, "operator": "RATP Transilien SNCF Ile de France Mobilités", "name_ru": null, "network": "Réseau Express Régional", "highway": null, "ref_FR_STI": null, "alt_name": "Laplace - Maison des Examens", "public_tra": null, "ref_FR_FAN": null, "subway": null, "mhs_inscri": null, "ref_mhs": null, "heritage": null, "heritage_o": null, "source_her": null, "rail": null, "importance": null, "train": null, "highspeed": null, "electrifie": null, "ref": "RER B", "old_name": null, "railway_sw": null, "crossing_l": null, "crossing_b": null, "crossing": null, "descriptio": null, "level": null, "ref_FR_uic": null, "tram": null, "barrier": null, "covered": null, "tactile_pa": null, "platforms": null, "start_date": null, "traffic_si": null, "traffic__1": null, "constructi": null, "supervised": null, "source_ref": null, "bicycle": null, "entrance": null }, "geometry": { "type": "Point", "coordinates": [ 2.3337534, 48.8078599 ] } }
]
}
